name: Score Submission

on:
  pull_request:
    paths:
      - "submissions/**/*.enc"

permissions:
  contents: write

jobs:
  score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout private evaluation repo
        uses: actions/checkout@v4
        with:
          repository: El-Ikram/Help_repo
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private_eval

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get submission file
        id: file
        run: |
          FILE=$(find submissions -name "*.enc" | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Decrypt submission
        env:
          SUBMISSION_PRIVATE_KEY: ${{ secrets.SUBMISSION_PRIVATE_KEY }}
        run: |
          python encryption/decrypt.py "${{ steps.file.outputs.file }}"

      - name: Evaluate submission
        id: eval
        run: |
          CSV_FILE="${{ steps.file.outputs.file }}"
          CSV_FILE="${CSV_FILE%.enc}.csv"

          SCORE=$(python competition/evaluate.py \
          "$CSV_FILE" \
          private_eval/test_labels.csv | grep SCORE | cut -d "=" -f2)

          echo "score=$SCORE" >> $GITHUB_OUTPUT

      - name: Append to leaderboard
        run: |
          echo "${{ github.actor }},${{ steps.eval.outputs.score }},$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> leaderboard/leaderboard.csv

      - name: Commit leaderboard
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leaderboard/leaderboard.csv
          git commit -m "Leaderboard update for ${{ github.actor }}" || exit 0
          git push origin HEAD:main
